DRIVERS-2411
mongodb/mongo-c-driver pull request #1124
Opened 2022-10-19 15:49 UTC by kevinAlbs

# Summary

- Implements integration tests proposed in https://github.com/mongodb/specifications/pull/1325

# Notes

The additions to the Python evergreen generation scripts are minimal. IMO the Python scripts are not significantly more readable than the Evergreen config YML. For this PR, I found it easier to start with Evergreen YML, then translate to the Python scripts.

2022-10-19 21:29 UTC, DmitryLukyanov commented on .evergreen/config.yml
> +        DRIVER_TOOLS=$(pwd)/drivers-evergreen-tools
DRIVER*S*_TOOLS

2022-10-20 01:44 UTC, DmitryLukyanov commented on .evergreen/config.yml
> +        DRIVER_TOOLS=$(pwd)/drivers-evergreen-tools
nit: If I understand this code correctly, this looks unnecessary if you use DRIVERS_TOOLS env variable

2022-10-20 15:50 UTC, DmitryLukyanov commented on .evergreen/config.yml
> +        DRIVERS_TOOLS=$(pwd)/drivers-evergreen-tools
NOTE: if you use DRIVERS_TOOLS, this value should already be assigned, at least this is what I saw in the c# driver (same in other places)

2022-10-20 15:50 UTC, DmitryLukyanov commented on .evergreen/config.yml
> +        DRIVER_TOOLS=$(pwd)/drivers-evergreen-tools
got it

2022-10-20 15:51 UTC, DmitryLukyanov commented on .evergreen/config.yml
> +        DRIVERS_TOOLS=$(pwd)/drivers-evergreen-tools
Missed your explanation above. It's a bit strange, but ok :)

2022-11-01 21:09 UTC, vector-of-bool requested changes
Sorry for the delayed review. Have some minor change requests.

2022-11-01 21:09 UTC, vector-of-bool commented on .evergreen/compile-test-azurekms.sh
> +    -DCMAKE_C_EXTENSIONS=OFF \
C-standard flags may change with #1138

2022-11-01 21:09 UTC, vector-of-bool commented on .evergreen/config.yml
> +        AZUREKMS_DST="~/" \
Use explicit `$HOME`. The "~/" may not expand as expected.

2022-11-01 21:09 UTC, vector-of-bool commented on .evergreen/config.yml
> +        git clone https://github.com/kevinAlbs/drivers-evergreen-tools.git --branch DRIVERS-2411 drivers-evergreen-tools
Clone branches with `--depth=1` if we don't need the full repo history.

2022-11-01 21:09 UTC, vector-of-bool commented on build/evergreen_config_lib/testazurekms.py
> +          LD_LIBRARY_PATH=./install \
Use `$PWD/install` for the LD path to prevent pwd-sensitivity.

2022-11-01 21:09 UTC, vector-of-bool commented on src/libmongoc/tests/test-azurekms.c
> +   if (!mongodb_uri) {
Need to check `keyName` and `keyVaultEndpoint` too.

2022-11-01 21:09 UTC, vector-of-bool commented on src/libmongoc/tests/test-azurekms.c
> +   ceopts = mongoc_client_encryption_opts_new ();
Merge decl+init

2022-11-01 21:09 UTC, vector-of-bool commented on src/libmongoc/tests/test-azurekms.c
> +   ce = mongoc_client_encryption_new (ceopts, &error);
Merge decl+init

2022-11-02 17:20 UTC, vector-of-bool approved these changes

2022-11-03 12:27 UTC, merged