Update news for 1.25.3
mongodb/mongo-c-driver pull request #1491
Opened 2023-12-13 03:10 UTC by adriandole

2023-12-13 12:36 UTC, kevinAlbs requested changes

2023-12-13 12:36 UTC, kevinAlbs commented on NEWS
> +  * Fix data race in `mongoc_cursor_get_host`.
```suggestion
  * Disable shared libmongoc targets if `ENABLE_SHARED=OFF`
```

To match wording in: https://github.com/mongodb/mongo-c-driver/releases/tag/1.25.3

The data race fix was included in 1.25.2. Suggested change is to include CDRIVER-4784,

2023-12-13 14:21 UTC, kkloberdanz approved these changes
Once Kevin's suggestion is implemented, looks good to me.

2023-12-27 20:34 UTC, closed without merging

2023-12-27 20:34 UTC, kevinAlbs commented
Changes were incorporated into https://github.com/mongodb/mongo-c-driver/commit/0da4704d32f80a9eac7d264f1fda2bd70ebe399d#diff-7ee66c4f1536ac84dc5bbff1b8312e2eef24b974b3e48a5c5c2bcfdf2eb8f3ce