CDRIVER-4572 Log database name in command_failed events
mongodb/mongo-c-driver pull request #1530
Opened 2024-02-07 00:49 UTC by adriandole

2024-02-13 18:59 UTC, eramongodb requested changes
Missing spec test sync with changes from https://github.com/mongodb/specifications/commit/e7ee829329400786e01279b4f37d4e440d1e9cfa (syncing the logging and unified spec invalid tests should be unnecessary since we don't currently test either). Add `find.json` to to `./src/libmongoc/tests/json/command_monitoring/unified` and update event monitoring handlers in `entity-map.c` to include database names for [failed](https://github.com/mongodb/mongo-c-driver/blob/acc9ea8f918611c6d76d6979d8d44d56dce5e97e/src/libmongoc/tests/unified/entity-map.c#L519) and [succeeded](https://github.com/mongodb/mongo-c-driver/blob/acc9ea8f918611c6d76d6979d8d44d56dce5e97e/src/libmongoc/tests/unified/entity-map.c#L544) events accordingly.

2024-02-13 18:59 UTC, eramongodb commented on src/libmongoc/src/mongoc/mongoc-apm.c
> +                                   const char *database_name,
Missing corresponding `event->database_name = database_name;`.

2024-02-13 18:59 UTC, eramongodb commented on src/libmongoc/src/mongoc/mongoc-apm.h
Missing `mongoc_apm_command_succeeded_get_database_name`.

2024-02-13 18:59 UTC, eramongodb commented on src/libmongoc/tests/test-mongoc-command-monitoring.c
> +   bson_destroy (&test->reply);
```suggestion

   bson_free (test->db);
   test->db = bson_strdup (mongoc_apm_command_failed_get_database_name (event));

   bson_destroy (&test->reply);
```
Potential memory leak. Ensure any prior value is deallocated before potentially being overwritten.

2024-02-13 18:59 UTC, eramongodb commented on src/libmongoc/tests/test-mongoc-command-monitoring.c
> +   test->db = bson_strdup (mongoc_apm_command_failed_get_database_name (event));
```suggestion

   bson_free(test->db);
   test->db = bson_strdup (mongoc_apm_command_failed_get_database_name (event));
```
Detected memory leak. Ensure any prior value is deallocated before potentially being overwritten.

2024-02-13 19:09 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-apm.h
> +   const mongoc_apm_command_failed_t *event);
Add doc pages for `mongoc_apm_command_failed_get_database_name` and the to-be-added `mongoc_apm_command_succeeded_get_database_name`. See `mongoc_apm_command_started_get_database_name.rst` for an example.

2024-04-23 21:52 UTC, eramongodb approved these changes

2024-04-24 19:41 UTC, merged