CDRIVER-5582 address Coverity issues
mongodb/mongo-c-driver pull request #1621
Opened 2024-05-30 20:52 UTC by rcsanchez97

Prevent integer overflow

Coverity CID: 138996

Evergreen patch build: https://spruce.mongodb.com/version/6658c7c7f2b873000746e815/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

2024-05-30 20:58 UTC, eramongodb requested changes

2024-05-30 20:58 UTC, eramongodb commented on src/libmongoc/src/mongoc/mongoc-scram.c
> +   BSON_ASSERT ((num_chars + 1) <= SIZE_MAX / sizeof (uint32_t));
```suggestion
   BSON_ASSERT (bson_cmp_less_equal_su (num_chars, SIZE_MAX / sizeof (uint32_t) - 1u));
```
Avoid integer comparison signedness warnings.

2024-05-30 20:58 UTC, eramongodb commented on src/libmongoc/src/mongoc/mongoc-scram.c
>     utf8_codepoints = bson_malloc (sizeof (uint32_t) * (num_chars + 1)); /* add one for trailing 0 value. */
Suggest also modifying this line following the new range assertion:
```c
utf8_codepoints = bson_malloc (sizeof (uint32_t) * ((size_t) num_chars + 1u)); /* add one for trailing 0 value. */
```

2024-05-30 22:19 UTC, rcsanchez97 commented
Updated full patch build: https://spruce.mongodb.com/version/6658f32012fd160007956501/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

2024-05-31 19:24 UTC, eramongodb approved these changes

2024-06-03 15:36 UTC, merged