CDRIVER-4820 check return values of `bson_snprintf`
mongodb/mongo-c-driver pull request #1642
Opened 2024-06-13 13:41 UTC by laurelxiang

[evergreen](https://spruce.mongodb.com/version/6669e4353d2b3f0007b8a217/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

Evergreen test failures look unrelated, but could be double checked.

See https://github.com/mongodb/mongo-c-driver/compare/master...kevinAlbs:mongo-c-driver:bson_snprintf-hints.CDRIVER-4820?expand=1 for more details.

2024-06-13 15:09 UTC, kkloberdanz approved these changes
Looks good! Nice to have this check!

2024-06-13 19:46 UTC, kevinAlbs reviewed
Looks good. Most feedback is suggested simplifications.

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-gridfs.c
> +   }
```suggestion
   BSON_ASSERT (req > 0);
```

Suggest only checking no error occurred. The `BSON_ASSERT (prefix_len + sizeof (".chunks") < sizeof (buf));` above checks that `buf` is large enough.

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-gridfs.c
> +   }
```suggestion
   BSON_ASSERT (req > 0);
```

Suggest only checking no error occurred. The `BSON_ASSERT (prefix_len + sizeof (".chunks") < sizeof (buf));` above checks that `buf` is large enough.

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/tests/test-mongoc-dns.c
> +mongoc_host_list_t *
```suggestion
static mongoc_host_list_t *
```

Suggest defining function as static since it is not accessed outside of this file.

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-read-prefs.c
> +   BSON_ASSERT ((size_t) req < sizeof str);
```suggestion
   BSON_ASSERT (bson_cmp_less_su (req, sizeof str));
```

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-topology-scanner.c
> +      BSON_ASSERT ((size_t) req < sizeof portstr);
```suggestion
      BSON_ASSERT (bson_cmp_less_su (req, sizeof portstr));
```

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-topology-scanner.c
> +   if (!bson_in_range_size_t_signed (req) || (size_t) req >= sizeof saddr.sun_path - 1) {
```suggestion
   if (bson_cmp_greater_equal_su (req, sizeof saddr.sun_path - 1)) {
```

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-util.c
> +      BSON_ASSERT ((size_t) req < 3);
```suggestion
      BSON_ASSERT (req < 3);
```

2024-06-13 19:46 UTC, kevinAlbs commented on src/libmongoc/src/mongoc/mongoc-util.c
> +      BSON_ASSERT ((size_t) req < 3);
```suggestion
      BSON_ASSERT (req < 3);
```

2024-06-14 14:19 UTC, laurelxiang commented on src/libbson/src/bson/bson-decimal128.c
> +      BSON_ASSERT (req > 0);
Added

2024-06-17 12:55 UTC, kevinAlbs requested changes

2024-06-17 17:40 UTC, kevinAlbs approved these changes

2024-06-17 19:36 UTC, merged