CDRIVER-5707 ignore unknown servers in aggregate-with-write check
mongodb/mongo-c-driver pull request #1723
Opened 2024-09-10 21:29 UTC by kevinAlbs

# Summary

Ignore unknown servers when checking to override read preferences for an aggregate-with-write.

Verified by this patch build: https://spruce.mongodb.com/version/66e0ad1ebdf6d3000745d0ba

# Background & Motivation

See CDRIVER-5707.

2024-09-10 22:10 UTC, joshbsiegel requested changes

2024-09-10 22:10 UTC, joshbsiegel commented on src/libmongoc/src/mongoc/mongoc-topology-description.c
> +   if (sd->type != MONGOC_SERVER_UNKNOWN && sd->max_wire_version < WIRE_VERSION_5_0) {
I think a similar additional check is needed in `mongoc_topology_description_select` here:
```cpp
if (optype == MONGOC_SS_AGGREGATE_WITH_WRITE && sd->max_wire_version < WIRE_VERSION_5_0) {
   /* The single server may be part of an unseen replica set that may not
    * support aggr-with-write operations on secondaries. Force the read
    * preference to use a primary. */
    if (must_use_primary) {
      *must_use_primary = true;
    }
  }
```
Sharded clusters were failing [here](https://spruce.mongodb.com/version/66e0ac5813acb00007aa8b0a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) without this check but [pass](https://spruce.mongodb.com/version/66e0b9b95889c300071c0e7a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with the addition.

2024-09-11 13:28 UTC, joshbsiegel approved these changes

2024-09-19 18:29 UTC, vector-of-bool approved these changes
LGTM

2024-09-19 20:10 UTC, merged