CDRIVER-5708 deprecate `mongoc_<obj>_command`
mongodb/mongo-c-driver pull request #1778
Opened 2024-10-23 19:50 UTC by kevinAlbs

# Summary

Deprecate `mongoc_<obj>_command`.

Document migrating to corresponding `mongoc_<obj>_command_simple`.

Verified by [this patch build](https://spruce.mongodb.com/version/671951525bedf30007bc2545).

# Background & Motivation

See CDRIVER-5708 for motivation for deprecating.

Previous documentation [noted]((https://mongoc.org/libmongoc/1.28.0/mongoc_client_command.html)) the `mongoc_<obj>_command` functions were "superseded" by `mongoc_<obj>_command_with_opts`, `mongoc_<obj>_read_command_with_opts`, `mongoc_<obj>_write_command_with_opts`, and `mongoc_client_read_write_<obj>_with_opts`.

Documentation has been updated to recommend migrating to `mongoc_<obj>_command_simple` for simplicity. Though the underlying call to `_mongoc_cursor_run_command` [indicates a read command](https://github.com/mongodb/mongo-c-driver/blob/9e42ae331ff079fc3ea2a8bad3d69063ddb7207f/src/libmongoc/src/mongoc/mongoc-cursor.c#L890), none of the read-specific behavior appears to apply. `mongoc_<obj>_command` [prohibits retry](https://github.com/mongodb/mongo-c-driver/blob/9e42ae331ff079fc3ea2a8bad3d69063ddb7207f/src/libmongoc/tests/test-mongoc-retryable-reads.c#L173-L174). Options are not supported, so a session cannot be passed. The read concern is not inherited from the client.

2024-10-23 21:58 UTC, eramongodb approved these changes

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/examples/migrating.c
> +main (int argc, char *argv[])
```suggestion
main (void)
```
Unused parameters.

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/doc/mongoc_database_command.rst
> +     BSON_GNUC_WARN_UNUSED_RESULT BSON_GNUC_DEPRECATED_FOR (mongoc_database_command_simple);
I believe these attribute-like macros should be omitted from documentation (similar to how `MONGOC_EXPORT` is omitted). These control compiler output but are not meant for users to read (these documentation pages serve that purpose instead).

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/doc/mongoc_database_command.rst
> +This function is superseded by :symbol:`mongoc_database_command_simple()`.
Should this be moved into the deprecation note instead?

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/examples/migrating.c
> +      if (!ok) {
```suggestion
      if (!mongoc_collection_command_simple (coll, cmd, NULL /* read prefs */, &reply, &error)) {
```
Simplification.

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/examples/migrating.c
> +      if (!ok) {
```suggestion
      if (!mongoc_client_command_simple (client, "db", cmd, NULL /* read prefs */, &reply, &error)) {
```
Simplification.

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/examples/migrating.c
> +      if (!ok) {
```suggestion
      if (!mongoc_database_command_simple (db, cmd, NULL /* read prefs */, &reply, &error)) {
```
Simplification.

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/doc/mongoc_database_command.rst
> +To migrate, use a non-deprecated alternative, like :symbol:`mongoc_database_command_simple`:
```suggestion
The above code block may be rewritten to use :symbol:`mongoc_database_command_simple` instead, as shown below:
```
Wording tweaks: indicate the code block below is equivalent to the code block above.

Suggestion also applies to the other doc pages.

2024-10-23 21:58 UTC, eramongodb commented on src/libmongoc/examples/basic_aggregation/map-reduce-advanced.c
Does this example need to be updated? Running the example locally against MongoDB 8.0.1 returns:

```
ERROR: 'inline' takes only numeric '1'
```

2024-10-23 21:58 UTC, eramongodb requested changes
Misclicked prior review.

2024-10-29 16:39 UTC, eramongodb approved these changes
Minor suggestion; otherwise, LGTM.

2024-10-29 16:39 UTC, eramongodb commented on src/libmongoc/doc/mongoc_client_command.rst
> +      This function is superseded by :symbol:`mongoc_client_command_simple()`.
```suggestion
      Use :symbol:`mongoc_client_command_simple()` instead.
```
Imperative language + consistency with release notes. Also applies to the other doc pages.

2024-11-04 18:13 UTC, vector-of-bool approved these changes
LGTM

2024-11-04 18:40 UTC, merged