CDRIVER-4010 support 'let' option for aggregate command
mongodb/mongo-c-driver pull request #810
Opened 2021-06-25 21:55 UTC by rcsanchez97

Full patch build: https://spruce.mongodb.com/version/60d5ee4be3c33111e05b9faa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

I checked quite a few of the failures in that patch build in every single case (with one exception*) the failure in the patch build was identical to the failure of the same task in the base commit.  *The one exception is a Valgrind test that had a hard failure in the base commit but which timed out in the patch build.

Based on this, it seems like the C driver already has the necessary support, so simply updating the CRUD JSON test is all we need to do.

2021-06-28 18:15 UTC, kevinAlbs approved these changes
LGTM, thank you for inspecting test logs to verify these tests did not introduce errors.

2021-06-28 18:22 UTC, kevinAlbs requested changes
Oops, I reviewed this before looking at https://github.com/mongodb/mongo-c-driver/pull/809. The test resync will be part of that PR.

Can you additionally update the documentation pages:
- http://mongoc.org/libmongoc/current/mongoc_database_aggregate.html
- http://mongoc.org/libmongoc/current/mongoc_collection_aggregate.html

To note the new option?

2021-06-29 14:42 UTC, rcsanchez97 commented
Sure.  I am guessing that I will also need to drop the test sync since
#809 handled that.

2021-07-01 20:14 UTC, kevinAlbs approved these changes
LGTM

2021-07-03 17:03 UTC, merged