CDRIVER-4098 Bump WIRE_VERSION_MIN from 3 to 6
mongodb/mongo-c-driver pull request #926
Opened 2022-01-13 18:25 UTC by eramongodb

Per CDRIVER-4098:

> MongoDB 3.4 reached end of life in January of 2020. MongoDB 3.6 (which reached end of life in April 2021, but seems likely to still exist in Atlas for some time) introduced OP_MSG, which replaced the previous wire protocol for MongoDB. 3.6 seems like the right new minimum server version.

Therefore, the minimum wire version supported by the C driver should now be wire version 6. Correspondingly, this PR modifies the `WIRE_VERSION_MIN` macro defined in [mongoc-client-private.h](https://github.com/mongodb/mongo-c-driver/blob/ee2001b90e9f04c83fb29ac0c67a70160a0d1fcb/src/libmongoc/src/mongoc/mongoc-client-private.h#L45) and raises it from 3 to 6.

## Bumping `WIRE_VERSION_MIN`

The minimum wire version is enforced in the client implementation by [_mongoc_topology_description_check_compatible()](https://github.com/mongodb/mongo-c-driver/blob/ee2001b90e9f04c83fb29ac0c67a70160a0d1fcb/src/libmongoc/src/mongoc/mongoc-topology-description.c#L1986), which is invoked by [mongoc_topology_description_handle_hello()](https://github.com/mongodb/mongo-c-driver/blob/ee2001b90e9f04c83fb29ac0c67a70160a0d1fcb/src/libmongoc/src/mongoc/mongoc-topology-description.c#L2130). There are also various feature compatibility checks spread throughout the client, tested as demanded by corresponding operations. These checks have been left unchanged. Followup changes to simplify or remove the client implementation according to the new minimum wire version are not included in this PR.

## `request` parameter for `mock_server_replies_to_find()`

Numerous tests are written using a pattern similar to the following:

```c
future = future_cursor_next (cursor, &doc);
request = mock_server_receives_request (server);
mock_server_replies_to_find (request, /* ... */);
```

Despite `mock_server_receives_request()` potentially returning a `NULL` result (on timeout, such as due to no compatible servers being found), the test code and `mock_server_replies_to_find()` assume `request` is not-null. A precondition check was therefore [added](https://github.com/mongodb/mongo-c-driver/commit/17eca57ace2f64c1cbbbaa41a2a81db8448ac024) to improve the resulting error message when this condition is violated.

## Minimum wire version compatibility error message

Previously, the C driver reports compatibility failure with [the following message](https://github.com/mongodb/mongo-c-driver/blob/ee2001b90e9f04c83fb29ac0c67a70160a0d1fcb/src/libmongoc/src/mongoc/mongoc-topology-description.c#L1991):

> Server at %{host_and_port} reports wire version %{max_wire_version}, but this version of libmongoc requires at least 3 (MongoDB 3.0)

The hardcoded wire version and server version numbers are [replaced with](https://github.com/mongodb/mongo-c-driver/commit/d2e972f7f004be43599f84a9d6bbc8db8232582e) substitution of `WIRE_VERSION_MIN` and a new `_mongoc_wire_version_to_server_version()` function to obtain the corresponding server version number:

> Server at %{host_and_port} reports wire version %{max_wire_version}, but this version of libmongoc requires at least %{WIRE_VERSION_MIN} (MongoDB %{server_version})

## Removal of Evergreen tasks

All tasks designed to be tested against MongoDB server versions earlier than 3.6 (corresponding to wire version < 6) [have been removed](https://github.com/mongodb/mongo-c-driver/commit/04dd838517d1999b0fbac7459b99a2b8eac1a7f3). 220 tasks were removed in total, bringing the total number of Evergreen tasks for the mongo-c-project down from 1040 to 820.

## Minimum wire version check in mock servers

The mock server creation functions were updated to [forbid `max_wire_version` arguments with values below `WIRE_VERSION_MIN`](https://github.com/mongodb/mongo-c-driver/commit/9237aed94578fb437218da8b0eb7fc221a1aac0a), and branches conditioned on wire version < 6 were removed accordingly. Tests that require specifying a `minWireVersion` lower than `WIRE_VERSION_MIN` (or a `maxWireVersion` greater than `WIRE_VERSION_MAX`) are still free to do so using the `mock_server_auto_hello()` function, [such as in `test_wire_version()`](https://github.com/mongodb/mongo-c-driver/blob/cdc3b16231b2033d6fd34fb1101c3b8a96a91116/src/libmongoc/tests/test-mongoc-client.c#L857).

## Test code conditioned on wire version < 6

All checks assuming wire version >= 6 [were removed](https://github.com/mongodb/mongo-c-driver/commit/6f0232ba9b693a7ece8bf205288d728c7ab1d6e9) for redundancy, and all tests requiring wire version < 6 were removed and remaining test names modified accordingly. The full diff of old tests vs. new tests are as follows:

```
Before                                                | After
/BulkOperation/opts/collation/multi/w0/wire4          <
/BulkOperation/opts/collation/multi/w0/wire5          | /BulkOperation/opts/collation/multi/w0
/BulkOperation/opts/collation/multi/w1/wire4          <
/BulkOperation/opts/collation/multi/w1/wire5          | /BulkOperation/opts/collation/multi/w1
/BulkOperation/opts/collation/w0/wire4                <
/BulkOperation/opts/collation/w0/wire5                | /BulkOperation/opts/collation/w0
/BulkOperation/opts/collation/w1/wire4                <
/BulkOperation/opts/collation/w1/wire5                | /BulkOperation/opts/collation/w1
/BulkOperation/update_arrayfilters/unsupported        <
/Client/command_with_opts/legacy                      <
/Cluster/command/notprimary                           <
/Cluster/command_error/op_query                       <
/Cluster/not_primary/pooled/op_msg                    | /Cluster/not_primary/pooled
/Cluster/not_primary/pooled/op_query                  <
/Cluster/not_primary/single/op_msg                    | /Cluster/not_primary/single
/Cluster/not_primary/single/op_query                  <
/Cluster/not_primary_auth/pooled/op_msg               | /Cluster/not_primary_auth/pooled
/Cluster/not_primary_auth/pooled/op_query             <
/Cluster/not_primary_auth/single/op_msg               | /Cluster/not_primary_auth/single
/Cluster/not_primary_auth/single/op_query             <
/Collection/aggregate/collation/wire4                 <
/Collection/aggregate/collation/wire5                 | /Collection/aggregate/collation
/Collection/count/collation/wire4                     <
/Collection/count/collation/wire5                     | /Collection/count/collation
/Collection/find_and_modify/write_concern_pre_32      <
/Collection/find_with_opts/collation/error            <
/Collection/index/collation/wire4                     <
/Collection/index/collation/wire5                     | /Collection/index/collation
/counters/op_getmore_killcursors                      <
/counters/op_query                                    <
/Cursor/client_kill_cursor/with_primary/wv4           <
/Cursor/client_kill_cursor/without_primary/wv4        <
/Cursor/kill/pooled/cmd                               <
/Cursor/kill/single/cmd                               <
/Database/aggregate/writeConcern                      <
/find_and_modify/collation/fail                       <
/find_and_modify/collation/ok                         | /find_and_modify/collation
/find_and_modify/find_and_modify/write_concern_pre_32 <
/ReadConcern/allowed/explicit                         | /ReadConcern/explicit
/ReadConcern/allowed/inherited                        | /ReadConcern/inherited
/ReadConcern/prohibited/explicit                      <
/ReadConcern/prohibited/inherited                     <
/WriteCommand/split_opquery_with_options              <
/WriteCommand/w0_legacy_insert_many                   <
/WriteCommand/w0_legacy_update_and_replace_validation <
/WriteCommand/w0_legacy_update_one                    <
/WriteConcern/allowed                                 | /WriteConcern
/WriteConcern/prohibited                              <
```

## Wire version integer literals -> wire version feature macros

All instances of the wire version being specified using an integer literal (e.g. `mock_server_with_auto_hello (6)`) [were updated](https://github.com/mongo [...]

2022-01-17 20:20 UTC, kevinAlbs requested changes
Nicely done. The test code removal and Evergreen matrix removal seems like a big step towards better maintainability. Thank you for splitting up the diff into logical commits.

2022-01-17 20:20 UTC, kevinAlbs commented on src/libmongoc/tests/test-mongoc-collection-find-with-opts.c
>     /* does NOT set secondaryOk, since this is a sharded topology */
```suggestion
   /* does NOT set $readPreference, since this is a sharded topology */
```

2022-01-17 20:20 UTC, kevinAlbs commented on src/libmongoc/tests/test-mongoc-collection-find.c
> +    */
```suggestion
```

secondaryOk is not applicable to OP_MSG.

2022-01-17 20:20 UTC, kevinAlbs commented on src/libmongoc/tests/test-mongoc-collection-find.c
>        /* only the secondaryOk bit is still in the query header */
```suggestion
```

2022-01-17 20:20 UTC, kevinAlbs commented on src/libmongoc/tests/test-mongoc-collection-find.c
>        /* only the secondaryOk bit is still in the query header */
```suggestion
```

2022-01-17 20:20 UTC, kevinAlbs commented on src/libmongoc/tests/test-mongoc-collection.c
>     /* does NOT set secondaryOk, since this is a sharded topology */
```suggestion
```

2022-01-18 17:32 UTC, eramongodb commented on src/libmongoc/tests/test-mongoc-collection-find-with-opts.c
>     /* does NOT set secondaryOk, since this is a sharded topology */
Will fix.

2022-01-18 17:32 UTC, eramongodb commented on src/libmongoc/tests/test-mongoc-sample-commands.c
> -   /* End Aggregation Example 4 */
Thank you for background. Was not aware. Will revert.

2022-01-18 17:32 UTC, eramongodb commented on src/libmongoc/tests/test-mongoc-read-prefs.c
> +   _test_find_command (uri, server, query_in, read_prefs, expected_op_msg);
Good spot. Will update.

2022-01-18 17:32 UTC, eramongodb commented on src/libmongoc/tests/test-mongoc-read-prefs.c
>                    const char *expected_query,
Will rename as suggested.

2022-01-18 17:32 UTC, eramongodb commented on build/evergreen_config_lib/variants.py
> -             '.test-asan .3.4',
Good spot. Will update.

2022-01-19 16:50 UTC, kevinAlbs approved these changes
LGTM!

2022-01-24 20:33 UTC, vector-of-bool approved these changes
Many many small changes, but nothing suspicious. LGTM!

2022-01-28 17:09 UTC, merged