fix CMake version check for OpenSSL 1.1+ on Windows
mongodb/mongo-c-driver pull request #973
Opened 2022-04-25 21:19 UTC by TheDorkKnight

As it stands, this check does not function as intended on the CMake versions that I tried (3.22 and 3.23).

I suspect it would not work from CMake 3.10 until CMake 3.70 (were such a version ever to exist); the comparison appears to a floating-point comparison instead of a version comparison.

I took the error message

> `requires CMake 3.7 or later`

at face value and assumed that `${CMAKE_VERSION} VERSION_GREATER_EQUAL 3.7` is correct instead of `${CMAKE_VERSION} VERSION_GREATER 3.7` which would be the direct translation from the previous version of the script.

2022-04-25 21:49 UTC, rcsanchez97 requested changes
Based on the CMake docs, the `VERSION_GREATER_EQUAL` test was introduced in CMake 3.7.  However, our build only requires CMake 3.1.  This will need to be updated to be functional CMake 3.1 before it can be merged.

2022-04-25 22:11 UTC, TheDorkKnight commented
Sounds good. Here's a link to the version comparisons [documentation link](https://cmake.org/cmake/help/latest/command/if.html#version-comparisons) for posterity.

As you said:
> if(<variable|string> VERSION_GREATER_EQUAL <variable|string>)
New in version 3.7:

2022-05-04 17:18 UTC, vector-of-bool approved these changes

2022-05-04 17:42 UTC, rcsanchez97 approved these changes

2022-05-04 17:43 UTC, merged